### ISSUE TITLE
rtx: broken emission texture (sky too) through glass 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [w23/xash3d-fwgs#284]
![изображение](https://user-images.githubusercontent.com/4449851/145877465-9bf7e7ce-f32a-4b8f-afec-8c6e6a25d3a0.png)

На c2a4e небо через стёкла тоже не видно!
![изображение](https://user-images.githubusercontent.com/4449851/146456475-9da4d1ec-9d0e-4254-972a-b491fe98eafc.png)

**Comment by MaxG2D** [comment]
The issue of the emissive can be fixed with following edit, however, the sky in glass is still broken, turning white instead of black.:

![Untitled](https://user-images.githubusercontent.com/88550439/146685921-3842040c-7e82-4f54-b818-6b21c4e6cbba.jpg)
![unknown](https://user-images.githubusercontent.com/88550439/146685933-a7739cba-97b0-4771-ac1b-fca427a38198.png)
![unknown2](https://user-images.githubusercontent.com/88550439/146685927-775aa8c0-76aa-4f91-8b73-74296fe861a9.png)
